apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  params:
  - name: GOALS
    description: The Maven goals to run
    type: array
    default:
    - "package"
  - name: MAVEN_MIRROR_URL
    description: The Maven bucketrepo- mirror
    type: string
    default: ""
  workspaces:
  - name: source
  steps:
    - name: mvn-settings
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      workingDir: /.m2
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          [[ -f /.m2/settings.xml ]] && \
          echo 'using existing /.m2/settings.xml' && \
          cat /.m2/settings.xml && exit 0

          [[ -n '$(params.MAVEN_MIRROR_URL)' ]] && \
          cat > /.m2/settings.xml <<EOF
          <settings>
            <mirrors>
              <mirror>
                <id>mirror.default</id>
                <name>mirror.default</name>
                <url>$(params.MAVEN_MIRROR_URL)</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

          [[ -f /.m2/settings.xml ]] && cat /.m2/settings.xml
          [[ -f /.m2/settings.xml ]] || echo skipping settings
      volumeMounts:
        - name: m2-repository
          mountPath: /.m2
    - name: mvn-goals
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)
      command:
        - /usr/bin/mvn
      args:
        - "$(params.GOALS)"
      volumeMounts:
        - name: m2-repository
          mountPath: /.m2
  volumes:
    - name: m2-repository
      emptyDir: {}
