apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kn
spec:
  params:
  - name: kn-image
    description: kn CLI container image to run this task
    default: gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
  - name: ARGS
    type: array
    description: kn CLI arguments to run
    default:
    - "help"
  resources:
    inputs:
    - name: image
      type: image
  steps:
  - name: kn
    image: "$(params.kn-image)"
    command: ["/ko-app/kn"]
    args: ["$(params.ARGS)"]
    # reference the container image resource in your taskrun/pipelinerun
    # parameters array as "--image=$(resources.inputs.image.url)"
