apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-build-kn-create-
spec:
  serviceAccountName: kn-deployer-account
  pipelineRef:
    name: buildah-build-kn-create
  resources:
    - name: image
      resourceRef:
        name: buildah-build-kn-create-image
  workspaces:
    - name: source
      persistentvolumeclaim:
        claimName: clone-source-pvc
  params:
    - name: GIT_URL
      value: "https://github.com/navidshaikh/helloworld-go"
    - name: ARGS
      value:
        - "service"
        - "create"
        - "hello"
        - "--revision-name=hello-v1"
        - "--image=$(inputs.resources.image.url)"
        - "--env=TARGET=Tekton"
        - "--service-account=kn-deployer-account"
