---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildah-build-kn-create-image
spec:
  type: image
  params:
    - name: url
      value: "quay.io/navidshaikh/helloworld-go"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
