---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terraform-cli
spec:
  workspaces:
  - name: source
  params:
  - name: ARGS
    description: The terraform cli commands to tun
    type: array
    default:
    - "--help"
  - name: terraform-secret
    description: The terraform secret with credentials
    type: string
    default: "terraform-creds"
  steps:
    - name: init
      image: quay.io/rcmendes/terraform-cli:latest
      workingDir: $(workspaces.source.path)
      command: ["/usr/local/bin/terraform"]
      args:
        - "init"
    - name: terraform-cli
      image: quay.io/rcmendes/terraform-cli:latest
      workingDir: /workspace/source
      command: ["/usr/local/bin/terraform"]
      args:
        - "$(params.ARGS)"
      envFrom:
        - secretRef:
            name: $(params.terraform-secret)
